version: '3'
services:
  ros-humble-ubuntu20:
    container_name: ros-humble-ubuntu20
    image: ros-humble-ubuntu20
    build:
      context: .
    runtime: nvidia
    volumes:
      - ./:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/root/.Xauthority
    working_dir: /home/ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
      - UID=1000
      - GID=1000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    